#!/bin/sh -ex

# source.list and pin configured via overlay
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

apt-get -y update
apt-get -y dist-upgrade
apt-get install -y libapache2-mod-mono mono-apache-server4

WEBROOT=/var/www
MONO_WEBROOT=/etc/mono-server4/conf.d/webroot

# configure apache
a2enmod rewrite

# create mono webroot site
mkdir -p $MONO_WEBROOT
cat >$MONO_WEBROOT/10_webroot<<EOF
# This is the configuration file
# for the webroot
path = $WEBROOT
alias = /
libs = /usr/lib/mono/2.0
EOF

cp -r /etc/mono-server2/conf.d/asp.net-examples /etc/mono-server4/conf.d/asp.net-examples

mono-server4-update

# create symlinks for samples (why do they hardcode paths?!)
SAMPLES=/usr/share/asp.net-demos
for f in mono-powered-big.png mono.png mono-xsp.css monobutton.png; do
    ln -s $SAMPLES/$f $WEBROOT/$f
done

apt-get autoremove -y
apt-get clean
